# .streamlit/config.toml

[theme]
primaryColor = "#00ADB5"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e222d"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

